
site_name: Multimodal Memory LLM and AI Agent
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true  # Enables \[ \] and \( \)

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter:
      enable_default_markdown: false

nav:
  - Home: index.md
  - Core Modules:
    - Deep Learning Foundations: deep_learning.md
    - Self-Supervised Learning: self-supervised.md
    - Transformer Fundamentals: transformers.md
    - Multimodal Embeddings: embeddings.md
    - LLM Frameworks and Architectures: llm.md
    - Memory Systems: memory.md
    - Tool Calling and Agent Capabilities: agents.md
    - Multi-Modal Language Models: multi_modal_LM.md
  - Advanced Topics:
    - Advanced Transformer Techniques: transformers_advanced.md
    - Inference Optimization: inference_optimization.md
    - GPT Architecture Evolution: gpt_architecture_evolution.md
    - Autonomous Systems Survey: autonomous_system/autonomous_systems_survey.md
    - Physical AI in Autonomous Driving: physical_ai_autonomous_driving.md
  - Notebooks:
    - Memory Example: notebooks/memory_example.ipynb
